### ISSUE TITLE
Support of functional updates (F, Func, Combinable)

### ISSUE THREAD

**Issue by M1ha-Shvn** [M1ha-Shvn/django-pg-bulk-update#38]

**Comment by proofit404** [comment]
Hi, thank you for the amazing library.

Is there anything I could help with to make this feature happen?

**Comment by M1hacka** [comment]
Hi.
This feature requires big redesign work on [`AbstractSetFunction`](https://github.com/M1hacka/django-pg-bulk-update/blob/a17e6e0d4aebd4a8144ad37fa88c29f7bdad8784/src/django_pg_bulk_update/set_functions.py#L77) class and its child classes, in order to make them compatible both with current function system and django's native (I use this feature in other projects, so I need back compatibility anyway).
Another thing to do (may be, not in this task) is to support functions in returning feature.
For now, I'm not sure when I have time to do this feature, and it will be less prior for me than https://github.com/M1hacka/django-pg-bulk-update/issues/33.
If you need it - you are free to submit a PR.

**Comment by M1ha-Shvn** [comment]
Here is [the PR](https://github.com/M1ha-Shvn/django-pg-bulk-update/pull/81)

**Comment by M1ha-Shvn** [comment]
Released [v3.5.0](https://github.com/M1ha-Shvn/django-pg-bulk-update/releases/tag/v3.5.0)
